name: event_truck
description: EventTruck is a lightweight, extensible, and type-safe event bus for managing event-driven architecture
version: 1.0.0-dev

homepage: https://www.contributors.info/repository/event_truck

repository: https://github.com/contributors-company/event_truck

issue_tracker: https://github.com/contributors-company/event_truck/issues

topics:
  - event-bus
  - events
  - stream
  - event-handling
  - event-listeners

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints:
  test:
