name: event_truck
description: A starting point for Dart libraries or applications.
version: 1.0.0

homepage: https://www.contributors.info/repository/fform

repository: https://github.com/contributors-company/event_truck

issue_tracker: https://github.com/contributors-company/event_truck/issues

topics:
  - form
  - validation
  - fields

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints:
  test:
